# Generated by Django 4.2.16 on 2024-10-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="type_user",
            field=models.CharField(default="Basic", max_length=10),
        ),
    ]
