# Generated by Django 4.2.16 on 2024-10-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_league"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="id",
        ),
        migrations.AddField(
            model_name="league",
            name="country",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="league",
            name="id_league",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="league",
            name="logo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="league",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
