# Generated by Django 4.2.16 on 2024-10-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_league_id_league_country_league_id_league_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("home_team", models.CharField(max_length=100)),
                ("home_team_logo", models.URLField()),
                ("away_team", models.CharField(max_length=100)),
                ("away_team_logo", models.URLField()),
                ("home_team_goals", models.IntegerField(default=0)),
                ("away_team_goals", models.IntegerField(default=0)),
                ("match_status", models.CharField(max_length=50)),
                ("home_odds", models.DecimalField(decimal_places=2, max_digits=10)),
                ("draw_odds", models.DecimalField(decimal_places=2, max_digits=10)),
                ("away_odds", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.league"
                    ),
                ),
            ],
        ),
    ]
