# Generated by Django 4.2.16 on 2024-10-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_match_id_match_id_fixture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="away_team_goals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team_goals",
            field=models.IntegerField(null=True),
        ),
    ]
