# Generated by Django 4.2.16 on 2024-10-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_match_away_odds_alter_match_draw_odds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_odds',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='draw_odds',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_odds',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
