# Generated by Django 4.2.16 on 2024-10-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_match_away_winner_match_home_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_winner',
        ),
    ]
