# Generated by Django 4.2.16 on 2024-10-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_match_away_winner_remove_match_home_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
