# Generated by Django 4.2.16 on 2024-10-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('national', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='away_odds',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='match',
            name='draw_odds',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_odds',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
