# Generated by Django 4.2.16 on 2024-10-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_teams_alter_match_away_odds_alter_match_away_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=50)),
                ('photo', models.URLField()),
                ('teams', models.ManyToManyField(related_name='players', to='core.teams')),
            ],
        ),
    ]
