# Generated by Django 4.2.16 on 2024-10-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
