# Generated by Django 4.2.16 on 2024-10-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_players_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='export',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
