# Generated by Django 4.2.16 on 2024-10-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_players_cards_red_players_cards_yellow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
