# Generated by Django 4.2.16 on 2024-10-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_players_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
