# Generated by Django 4.2.16 on 2024-10-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_teams_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='confederation',
        ),
        migrations.AddField(
            model_name='league',
            name='confederacion',
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
    ]
