# Generated by Django 4.2.16 on 2024-10-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_teams_confederation_league_confederacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rewards_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
