# Generated by Django 4.2.16 on 2024-10-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_rewards_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
