# Generated by Django 4.2.16 on 2024-10-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_monthlyraffle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyraffle',
            name='ligue',
            field=models.CharField(choices=[('oro', 'Oro'), ('plata', 'Plata'), ('bronce', 'Bronce')], max_length=15),
        ),
    ]
