# Generated by Django 4.2.16 on 2024-10-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_monthlyraffle_ligue'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
