# Generated by Django 4.2.16 on 2024-10-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_league_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=155)),
                ('year', models.PositiveSmallIntegerField(default=1900)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.players')),
            ],
        ),
    ]
