# Generated by Django 4.2.16 on 2024-10-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='teams',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
