# Generated by Django 4.2.16 on 2024-10-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_achievements_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
