# Generated by Django 4.2.16 on 2024-11-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='token_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
