# Generated by Django 4.2.16 on 2024-11-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_players_token_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_in_order',
            field=models.BooleanField(default=False),
        ),
    ]
