# Generated by Django 4.2.16 on 2024-11-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_token_is_in_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.token'),
        ),
    ]
