# Generated by Django 4.2.16 on 2024-11-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_order_token_name_alter_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='order',
            field=models.IntegerField(default=999),
        ),
    ]
